### ISSUE TITLE
Module build failed: Error: /Users/herrjosua/WebstormProjects/ui-docs/src/app/ui/buttons/button.component.ts is not part of the compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.

### ISSUE THREAD

**Issue by herrjosua** [ui-jar/ui-jar#33]
I'm trying to integrate ui-jar into my work project, but I keep getting the same error no matter what I try. The error I'm getting is `Module build failed: Error: /Users/herrjosua/WebstormProjects/ui-docs/src/app/ui/buttons/button.component.ts is not part of the compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.`. 

I'm not sure how to resolve this issue. The only real difference I can see is that the angular-cli version is different (`1.2.1` vs. `1.6.0`).

My `package.json`:
```
{
  "name": "ui-docs",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "ui-jar": "node node_modules/ui-jar/dist/bin/cli.js --directory ./src/app/ --includes \\.ts$",
    "start-ui-jar-example": "npm run ui-jar && ng serve --port 4201 --app ui-jar"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14",
    "uswds": "^1.4.2",
    "bourbon": "^4.3.4",
    "bourbon-neat": "^1.9.0",
    "@fortawesome/fontawesome-free-webfonts": "^1.0.3"
  },
  "devDependencies": {
    "@angular-devkit/core": "0.0.29",
    "@angular-devkit/schematics": "0.0.52",
    "@angular/cli": "1.6.0",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2",
    "ui-jar": "^1.1.3"
  }
}
```
And the full stack trace:

```
Generating resources...
Generated resources successfully.
** NG Live Development Server is listening on localhost:4201, open your browser on http://localhost:4201/ **
Date: 2018-05-31T19:04:31.063Z                                                          
Hash: 79e1f1a051d1afbc14fa
Time: 5837ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 8.94 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 616 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 61.7 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 8.91 MB [initial] [rendered]

ERROR in ./src/app/ui/buttons/button-primary.directive.ts
Module build failed: Error: /Users/herrjosua/WebstormProjects/ui-docs/src/app/ui/buttons/button-primary.directive.ts is not part of the compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (/Users/herrjosua/WebstormProjects/ui-docs/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:643:23)
    at plugin.done.then (/Users/herrjosua/WebstormProjects/ui-docs/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
 @ ./node_modules/ui-jar/temp/__ui-jar-temp-module-9389092cc79aebffa80e08839da6a5c4.js 12:33-96
 @ ./node_modules/ui-jar/temp/__ui-jar-temp.js
 @ ./node_modules/ui-jar/dist/src/app/app.module.js
 @ ./node_modules/ui-jar/dist/index.js
 @ ./ui-jar/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./ui-jar/main.ts
ERROR in ./src/app/ui/buttons/button.component.ts
Module build failed: Error: /Users/herrjosua/WebstormProjects/ui-docs/src/app/ui/buttons/button.component.ts is not part of the compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (/Users/herrjosua/WebstormProjects/ui-docs/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:643:23)
    at plugin.done.then (/Users/herrjosua/WebstormProjects/ui-docs/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
 @ ./node_modules/ui-jar/temp/__ui-jar-temp-module-9389092cc79aebffa80e08839da6a5c4.js 11:25-80
 @ ./node_modules/ui-jar/temp/__ui-jar-temp.js
 @ ./node_modules/ui-jar/dist/src/app/app.module.js
 @ ./node_modules/ui-jar/dist/index.js
 @ ./ui-jar/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./ui-jar/main.ts

webpack: Failed to compile.
```

And finally the angular-cli.json file

```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "ui-docs"
  },
  "apps": [
    {
      "name": "app",
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "styles.scss"
      ],
      "scripts": [],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    },
    {
      "name": "ui-jar",
      "root": "ui-jar",
      "outDir": "dist-ui-jar",
      "assets": [
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "tsconfig": "tsconfig.app.json",
      "prefix": "app",
      "styles": [
        "styles.scss"
      ],
      "scripts": [],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "src/tsconfig.spec.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "e2e/tsconfig.e2e.json",
      "exclude": "**/node_modules/**"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "scss",
    "component": {}
  }
}

```

I have a standalone project that is working with no issues and is viewable [here](https://github.com/herrjosua/test-ui-jar)

**Comment by nording** [comment]
Does it work of you add following to your "tsconfig.app.json" in your /ui-jar directory?

...
"exclude": [
    "test.ts",
    "**/*.spec.ts",
    "../**/*.spec.ts" , <-- add this line
],
"include": [
    "**/*.ts",     <-- add this line
    "../src/**/*.ts" <-- add this line
]
...
